Courses/Areas/Admin/Controllers/CategoryController.cs
using Courses.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Courses.Models;
using Courses.Data;
using AutoMapper;

namespace Courses.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CategoryController : Controller
    {
        private readonly CategoryService categoryService;

        private readonly IMapper mapper;

        public CategoryController()
        {
            categoryService = new CategoryService();
            mapper = AutoMapperConfig.Mapper;
        }

        // GET: Admin/Category
        public ActionResult Index()
        {
            var categories = categoryService.ReadAll();

            var categoriesList = mapper.Map<List<CategoryModel>>(categories);

            return View(categoriesList);
        }

        public ActionResult Create()
        {
            var categoryModel = new CategoryModel();
            InitMainCategories(null, ref categoryModel);
            return View(categoryModel);
        }

        [HttpPost]
        public ActionResult Create(CategoryModel data)
        {
            var newCategory = mapper.Map<Category>(data);
                 newCategory.Category2 = null;
                int creationResult = categoryService.Create(newCategory);

                if(creationResult == -2)
                {
                InitMainCategories(null, ref data);

                ViewBag.Message = "Category Name is exists!";
                    return View (data);
                }

                return RedirectToAction("Index");
            
        }

        public ActionResult Edit(int? id)
        {
            if(id == null || id == 0)
            {
                return RedirectToAction("index", "Home");
            }

            var currentCategory = categoryService.ReadById(id.Value);

            if(currentCategory == null)
            {
                return HttpNotFound($"This category ({id}) not found! ");
            }
            var categoryModel = new CategoryModel
            {
                Id = currentCategory.ID,
                Name = currentCategory.Name,
                ParentId = currentCategory.Parent_id
            };

            InitMainCategories(currentCategory.ID, ref categoryModel);

            return View(categoryModel);
        }
        [HttpPost]
        public ActionResult Edit(CategoryModel data)
        {
            
                var updatedCategory = new Category
                {
                    ID = data.Id,
                    Name = data.Name,
                    Parent_id = data.ParentId
                };
                var result = categoryService.Update(updatedCategory);

                if (result == -2)
                {
                    ViewBag.Message = "Category Name is exists!";
                    InitMainCategories(data.Id, ref data);
                return View(data);
                }
                else if (result > 0)
                {
                    ViewBag.Success = true;
                    ViewBag.Message = $"Category ({data.Id}) updated successfully";
                }
                else
                {
                    ViewBag.Message = $"An error occured!";
                }
            InitMainCategories(data.Id, ref data);
            return View(data);
        }

        public ActionResult Delete(int? Id)
        {
            if(Id != null)
            {
                var category = categoryService.ReadById(Id.Value);
                var categoryInfo = new CategoryModel
                {
                    Id = category.ID,
                    Name = category.Name,
                    ParentName = category.Category2?.Name
                };

                return View(categoryInfo);
            }
            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult DeleteConfirmed(int? Id)
        {
            if(Id!=null)
            {
              var deleted =   categoryService.Delete(Id.Value);
                if(deleted)
                {
                    return RedirectToAction("Index");
                }
                return RedirectToAction("Delete", new { Id = Id });
            }
            return HttpNotFound();
        }

        private void InitMainCategories(int? categoryToExclude, ref CategoryModel categoryModel)
        {
            var categoriesList = categoryService.ReadAll();

            if(categoryToExclude!=null)
            {
                var currentcategory = categoriesList.Where(c => c.ID == categoryToExclude).FirstOrDefault();
                categoriesList.Remove(currentcategory);
            }

            categoryModel.MainCategories = new SelectList(categoriesList, "ID", "Name");
        }
    }
}

Courses/Areas/Admin/Controllers/TrainersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Courses.Data;

namespace Courses.Areas.Admin.Controllers
{
    [Authorize(Roles = "Admin")]
    public class TrainersController : Controller
    {
        private Courses_DBEntities1 db = new Courses_DBEntities1();

        // GET: Admin/Trainers
        public async Task<ActionResult> Index()
        {
            return View(await db.Trainers.ToListAsync());
        }

        // GET: Admin/Trainers/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trainer trainer = await db.Trainers.FindAsync(id);
            if (trainer == null)
            {
                return HttpNotFound();
            }
            return View(trainer);
        }

        // GET: Admin/Trainers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Admin/Trainers/Create
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "ID,Name,Email,Description,Website,Creation_Date")] Trainer trainer)
        {
            if (ModelState.IsValid)
            {
                db.Trainers.Add(trainer);
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }

            return View(trainer);
        }

        // GET: Admin/Trainers/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trainer trainer = await db.Trainers.FindAsync(id);
            if (trainer == null)
            {
                return HttpNotFound();
            }
            return View(trainer);
        }

        // POST: Admin/Trainers/Edit/5
        // Afin de déjouer les attaques par sur-validation, activez les propriétés spécifiques que vous voulez lier. Pour 
        // plus de détails, voir  https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "ID,Name,Email,Description,Website,Creation_Date")] Trainer trainer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(trainer).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(trainer);
        }

        // GET: Admin/Trainers/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Trainer trainer = await db.Trainers.FindAsync(id);
            if (trainer == null)
            {
                return HttpNotFound();
            }
            return View(trainer);
        }

        // POST: Admin/Trainers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            Trainer trainer = await db.Trainers.FindAsync(id);
            db.Trainers.Remove(trainer);
            await db.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

Courses/Controllers/CourseController.cs
using AutoMapper;
using Courses;
using Courses.Data;
using Courses.Models;
using Courses.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Courses.Controllers
{
    public class CourseController : Controller
    {
        private readonly IMapper mapper;
        private readonly CourseService courseService;
        public CourseController()
        {
            mapper = AutoMapperConfig.Mapper;

            courseService = new CourseService();
        }
        // GET: Course
        public ActionResult Index()
        {
            var courses = courseService.ReadAll();
            return View(mapper.Map<List<Course>, List<CourseModel>>(courses));
        }

        public ActionResult Info(int? Id)
        {
            if (Id == null || Id == 0)
                return HttpNotFound("This course not found!");

            var courseInfo = courseService.Get(Id.Value);
            if (courseInfo == null)
                return HttpNotFound("This course not found!");

            var mappedCourseInfo = mapper.Map<Course, CourseModel>(courseInfo);

            return View(mappedCourseInfo);
        }


        public ActionResult Subscribe(int Id)
        {
            if (!Request.IsAuthenticated)
            {
                return RedirectToAction("Login", "Account", new { returnUrl = $"/Course/Subscribe/{Id}" });
            }

            return View();
        }

    }
}

Courses/Controllers/DefaultController.cs
using AutoMapper;
using Courses.Data;
using Courses.Models;
using Courses.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Courses.Controllers
{
    public class DefaultController : Controller
    {
        private readonly IMapper mapper;
        private readonly CourseService courseService;
        public DefaultController()
        {
            mapper = AutoMapperConfig.Mapper;

            courseService = new CourseService();
        }
        // GET: Course
        public ActionResult Index()
        {
            var courses = courseService.ReadAll();
            return View(mapper.Map<List<Course>, List<CourseModel>>(courses));
        }
    }
}

Courses/Areas/Admin/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Coursat Web @ViewBag.Title </title>
    <link href="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/style.min.css" rel="stylesheet" />
    <link href="~/css/styles.css" rel="stylesheet" />
    <script src="https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body class="sb-nav-fixed">
    <nav class="sb-topnav navbar navbar-expand navbar-dark bg-dark">
        <!-- Navbar Brand-->
        <a class="navbar-brand ps-3" href="index.html">Coursaty</a>
        <!-- Sidebar Toggle-->
        <button class="btn btn-link btn-sm order-1 order-lg-0 me-4 me-lg-0" id="sidebarToggle" href="#!"><i class="fas fa-bars"></i></button>
        <!-- Navbar Search-->
        <form class="d-none d-md-inline-block form-inline ms-auto me-0 me-md-3 my-2 my-md-0">
            <div class="input-group">
                <input class="form-control" type="text" placeholder="Search for..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
                <button class="btn btn-primary" id="btnNavbarSearch" type="button"><i class="fas fa-search"></i></button>
            </div>
        </form>
        <!-- Navbar-->
        <ul class="navbar-nav ms-auto ms-md-0 me-3 me-lg-4">
            @Html.Partial("_LoginPartial")
        </ul>
    </nav>
    <div id="layoutSidenav">
        <div id="layoutSidenav_nav">
            <nav class="sb-sidenav accordion sb-sidenav-dark" id="sidenavAccordion">
                <div class="sb-sidenav-menu">
                    <div class="nav">
                        <div class="sb-sidenav-menu-heading">Core</div>
                        <a class="nav-link" href="@Url.Action("Index", "Default")">
                            <div class="sb-nav-link-icon"><i class="fas fa-tachometer-alt"></i></div>
                            Dashboard
                        </a>

                        <a class="nav-link" href="@Url.Action("Index", "Trainers")">
                            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                            Trainers
                        </a>

                        <a class="nav-link" href="@Url.Action("Index", "Category")">
                            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                            Categories
                        </a>

                        <a class="nav-link" href="@Url.Action("Index", "Course")">
                            <div class="sb-nav-link-icon"><i class="fas fa-chart-area"></i></div>
                            Courses
                        </a>
                    </div>
                </div>
                <div class="sb-sidenav-footer">
                    <div class="small">Logged in as:</div>
                    Coursaty
                </div>
            </nav>
        </div>
        <div id="layoutSidenav_content">
            <main>
                <div class="container-fluid px-4">
                    <h1 class="mt-4">Dashboard</h1>
                    <ol class="breadcrumb mb-4">
                        <li class="breadcrumb-item active">Dashboard</li>
                    </ol>
                  @RenderBody()
                </div>
            </main>
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2023</div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/js/scripts.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" crossorigin="anonymous"></script>
    <script src="~/assets/demo/chart-area-demo.js"></script>
    <script src="~/assets/demo/chart-bar-demo.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/simple-datatables@7.1.2/dist/umd/simple-datatables.min.js" crossorigin="anonymous"></script>
    <script src="js/datatables-simple-demo.js"></script>
</body>
</html>

Courses/Areas/Admin/Views/Shared/_OfflineLayout.cshtml
@{
    Layout = null;
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Courses Admin</title>
    <link href="~/css/styles.css" rel="stylesheet" />
    <script src="~/https://use.fontawesome.com/releases/v6.3.0/js/all.js" crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
    <div id="layoutAuthentication">
        <div id="layoutAuthentication_content">
            <main>
                <div class="container">
                    @RenderBody();
                </div>
            </main>
        </div>
        <div id="layoutAuthentication_footer">
            <footer class="py-4 bg-light mt-auto">
                <div class="container-fluid px-4">
                    <div class="d-flex align-items-center justify-content-between small">
                        <div class="text-muted">Copyright &copy; Your Website 2023</div>
                        <div>
                            <a href="#">Privacy Policy</a>
                            &middot;
                            <a href="#">Terms &amp; Conditions</a>
                        </div>
                    </div>
                </div>
            </footer>
        </div>
    </div>
    <script src="~/https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" crossorigin="anonymous"></script>
    <script src="~/js/scripts.js"></script>
</body>
</html>